
package com.ighing.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClienteService", targetNamespace = "http://service.ighing.com/", wsdlLocation = "http://localhost:9090/soap-ws-ighing/cliente-service?wsdl")
public class ClienteService_Service
    extends Service
{

    private final static URL CLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTESERVICE_EXCEPTION;
    private final static QName CLIENTESERVICE_QNAME = new QName("http://service.ighing.com/", "ClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/soap-ws-ighing/cliente-service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTESERVICE_WSDL_LOCATION = url;
        CLIENTESERVICE_EXCEPTION = e;
    }

    public ClienteService_Service() {
        super(__getWsdlLocation(), CLIENTESERVICE_QNAME);
    }

    public ClienteService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTESERVICE_QNAME, features);
    }

    public ClienteService_Service(URL wsdlLocation) {
        super(wsdlLocation, CLIENTESERVICE_QNAME);
    }

    public ClienteService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTESERVICE_QNAME, features);
    }

    public ClienteService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteService
     */
    @WebEndpoint(name = "ClienteServicePort")
    public ClienteService getClienteServicePort() {
        return super.getPort(new QName("http://service.ighing.com/", "ClienteServicePort"), ClienteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteService
     */
    @WebEndpoint(name = "ClienteServicePort")
    public ClienteService getClienteServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ighing.com/", "ClienteServicePort"), ClienteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTESERVICE_EXCEPTION!= null) {
            throw CLIENTESERVICE_EXCEPTION;
        }
        return CLIENTESERVICE_WSDL_LOCATION;
    }

}
