
package com.ighing.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteService", targetNamespace = "http://service.ighing.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteService {


    /**
     * 
     * @return
     *     returns java.util.List<com.ighing.service.Cliente>
     */
    @WebMethod
    @WebResult(name = "cliente", targetNamespace = "")
    @RequestWrapper(localName = "consultarCliente", targetNamespace = "http://service.ighing.com/", className = "com.ighing.service.ConsultarCliente")
    @ResponseWrapper(localName = "consultarClienteResponse", targetNamespace = "http://service.ighing.com/", className = "com.ighing.service.ConsultarClienteResponse")
    @Action(input = "http://service.ighing.com/ClienteService/consultarClienteRequest", output = "http://service.ighing.com/ClienteService/consultarClienteResponse")
    public List<Cliente> consultarCliente();

    /**
     * 
     * @param cliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "crearCliente", targetNamespace = "http://service.ighing.com/", className = "com.ighing.service.CrearCliente")
    @ResponseWrapper(localName = "crearClienteResponse", targetNamespace = "http://service.ighing.com/", className = "com.ighing.service.CrearClienteResponse")
    @Action(input = "http://service.ighing.com/ClienteService/crearClienteRequest", output = "http://service.ighing.com/ClienteService/crearClienteResponse")
    public String crearCliente(
        @WebParam(name = "cliente", targetNamespace = "")
        Cliente cliente);

}
